<?php
require_once dirname(__DIR__) . '/kgs-core/bootstrap.php';
session_start();

$client = GoogleService::userClient();
if (!isset($_GET['code'])) exit("Authentication failed.");

$token = $client->fetchAccessTokenWithAuthCode($_GET['code']);
$client->setAccessToken($token);

$user = (new \Google\Service\Oauth2($client))->userinfo->get();
$email = strtolower(trim($user->email));

// Check the Whitelist generated by the worker
$whitelistPath = ROOT_PATH . "kgs-cache/google/authorized_users.json";
$allowed = file_exists($whitelistPath) ? json_decode(file_get_contents($whitelistPath), true) : [];

if (!in_array($email, $allowed)) {
    error_log("Unauthorized editor login attempt: " . $email);
    exit("Access Denied: $email is not on the authorized editors list.");
}

$_SESSION['user_name'] = $user->name;
$_SESSION['logged_in'] = true;
header('Location: live-feed-post.php');
exit;