<?php
/**
 * ROUTER (APPLICATION ENTRY ORCHESTRATOR - Hybrid Sheet-Driven Version)
 * 
 * Responsibility:
 * - Resolve route via Google Sheets Sitemap (kgs-cache/google/sitemap.json)
 * - Fallback to physical kgs-content folders for legacy/static pages.
 * - Map "Page Templates" to component stacks.
 * - Manage layout sandwich (header/start/end/footer).
 */

class Router
{
    private array $aliases = [];

    public function alias(string $from, string $to): void { $this->aliases[trim($from, '/')] = trim($to, '/'); }
    public function loadAliasesFromSheet(array $rows): void { $this->applyAliasRows($rows); }

    /**
     * Main Entry Point
     */
    public function dispatch(string $route): void
    {
        // 1. Route Normalization & Aliasing
        $route = trim($route, '/') ?: 'home';
        if (isset($this->aliases[$route])) { $route = $this->aliases[$route]; }
        $route = str_replace(['..', '\\'], '', $route);

        /*
        |--------------------------------------------------------------------------
        | RENDERER PRE-LOAD (TASK 9 & 36 FIX)
        |--------------------------------------------------------------------------
        | Pre-loading ensures render_component() is available even for 404 pages 
        | where the footer depends on it.
        */
        require_once ROOT_PATH . 'app/components/renderer.php';

        /*
        |--------------------------------------------------------------------------
        | PAGE RESOLUTION (HYBRID MODE)
        |--------------------------------------------------------------------------
        */
        // A. Attempt to load from Spreadsheet Sitemap (Generated by Task 12)
        $page = $this->loadFromSitemap($route);

        // B. Fallback to physical folders (kgs-content/pages/...)
        if (!$page) {
            $cms = ServiceContainer::get('cms');
            $page = $cms ? $cms->load($route) : null;
        }

        // 404 Handler: Natives the 404 into the site layout
        if (!$page || (isset($page['components'][0]['type']) && $page['components'][0]['type'] === 'error-404')) {
            http_response_code(404);
            $this->renderErrorPage("404 - Page Not Found", "The requested page does not exist.");
            return;
        }

        // Meta & Layout Setup
        $meta = $page['meta'] ?? [];
        $components = $page['components'] ?? [];
        
        /**
         * LAYOUT RESOLUTION [TASK 24 FIX]
         * Prioritizes the layout defined in the spreadsheet (meta['layout'])
         */
        $layout = !empty($meta['layout']) ? $meta['layout'] : 'default';
        $currentRoute = $route;

        /*
        |--------------------------------------------------------------------------
        | OUTPUT GENERATION (The Sandwich)
        |--------------------------------------------------------------------------
        */
        include ROOT_PATH . 'app/layouts/header.php';

        $layoutStart = ROOT_PATH . "app/layouts/page/{$layout}-start.php";
        if (file_exists($layoutStart)) { 
            include $layoutStart; 
        } else {
            include ROOT_PATH . "app/layouts/page/default-start.php";
        }

        ob_start();
        try {
            foreach ($components as $component) {
                // FIXED: Using $compType to prevent variable shadowing ($type) for sidebars
                $compType = $component['type'] ?? '';
                $data     = $component['data'] ?? [];

                // HYDRATE: Inject global config or constants via @tokens
                $data = $this->hydrateComponentData($compType, $data);

                render_component($compType, $data);
            }
        } catch (Throwable $e) {
            echo '<div class="alert alert-danger">Pipeline Error: ' . htmlspecialchars($e->getMessage()) . '</div>';
        }
        echo ob_get_clean();

        $layoutEnd = ROOT_PATH . "app/layouts/page/{$layout}-end.php";
        if (file_exists($layoutEnd)) { 
            include $layoutEnd; 
        } else {
            include ROOT_PATH . "app/layouts/page/default-end.php";
        }

        include ROOT_PATH . 'app/layouts/footer.php';
    }

	private function loadFromSitemap(string $route): ?array
	{
		$path = ROOT_PATH . 'kgs-cache/google/sitemap.json';
		if (!file_exists($path)) return null;
		$sitemap = json_decode(file_get_contents($path), true);
		
		if (!isset($sitemap[$route])) return null;
		$row = $sitemap[$route];

		$template = $row['template'] ?? 'Standard';
		
		// RESOLVE PREFIX: Use Column J if it exists, fallback to route-slug
		$prefix = !empty($row['prefix']) ? $row['prefix'] : str_replace('/', '_', $route);

		$components = [];
		switch ($template) {
			case 'Home':
				$components = [
					['type' => 'hero', 'data' => ['image' => '@hero_img', 'hero_title' => '@hero_title', 'mobile_view' => 'full']],
					['type' => 'smart-grid', 'data' => ['prefix' => 'home', 'row' => 1]],
					['type' => 'smart-grid', 'data' => ['prefix' => 'home', 'row' => 2]],
					['type' => 'school-highlights', 'data' => ['doc_id' => '@school_highlights_doc_id']],
					['type' => 'live-feed',  'data' => ['limit' => 3]]
				];
				break;

			case 'Directory':
				$components = [
					['type' => 'page-header', 'data' => ['title' => $row['title']]],
					['type' => 'people-list', 'data' => ['type' => $row['data_id'], 'show_photos' => 'true']]
				];
				break;

			// NEW: Specific Case for School Board based on your Layout Plan
			case 'School Board':
				$components = [
					['type' => 'page-header', 'data' => ['title' => $row['title']]],
					['type' => 'google-doc-content', 'data' => ['doc_id' => $row['doc_id']]],
					['type' => 'smart-grid', 'data' => ['prefix' => $prefix, 'row' => 1]],
					['type' => 'smart-grid', 'data' => ['prefix' => $prefix, 'row' => 2]]
				];
				break;

			case 'Standard':
			default:
				$components[] = ['type' => 'page-header', 'data' => ['title' => $row['title']]];
				if (!empty($row['doc_id'])) {
					$components[] = ['type' => 'google-doc-content', 'data' => ['doc_id' => $row['doc_id']]];
				}
				$components[] = ['type' => 'smart-grid', 'data' => ['prefix' => $prefix, 'row' => 1]];
				break;
		}

		if ($route !== 'home') {
			$components[] = ['type' => 'link-tiles', 'data' => ['source_type' => 'site_menu']];
		}

		return [
			'meta' => [
				'title'   => $row['title'], 
				'layout'  => $row['layout'] // Prioritize spreadsheet layout (e.g. school-board)
			],
			'components' => $components
		];
	}

    /**
     * AUTOMATIC CONFIG HYDRATION
     */
    private function hydrateComponentData(string $type, array $data): array
    {
        foreach ($data as $key => $value) {
            if (is_string($value) && str_starts_with($value, '@')) {
                $configKey = substr($value, 1);
                $data[$key] = config($configKey);
            }
        }
        return $data;
    }

    private function applyAliasRows(array $rows): void 
    {
        foreach ($rows as $row) {
            $alias = trim($row['alias'] ?? $row[0] ?? '');
            $route = trim($row[1] ?? '');
            if ($alias && $route) $this->aliases[$alias] = $route;
        }
    }

    private function renderErrorPage($title, $message) 
    {
        $meta = ['title' => $title];
        include ROOT_PATH . 'app/layouts/header.php';
        echo "<div class='container my-5 py-5 text-center'><h1 class='display-1 text-muted'>404</h1><h3>$title</h3><p>$message</p></div>";
        include ROOT_PATH . 'app/layouts/footer.php';
    }

    public static function getLayout(array $page): string
    {
        return $page['meta']['layout'] ?? 'default';
    }
}